### ISSUE TITLE
es-iterator-helpers tried to access call-bind

### ISSUE THREAD

**Issue by lewandom** [es-shims/iterator-helpers#3]
This error shows up in the context of `eslint-config-next` with Yarn PnP:

`- info Linting and checking validity of types .- error ESLint: Failed to load plugin 'react' declared in '.eslintrc.json » eslint-config-next/core-web-vitals » redacted/.yarn/__virtual__/eslint-config-next-virtual-3dd005a3fc/0/cache/eslint-config-next-npm-13.4.16-745205b385-c4b6849c4b.zip/node_modules/eslint-config-next/index.js': es-iterator-helpers tried to access call-bind, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.  Required package: call-bind Required by: es-iterator-helpers@npm:1.0.12 (via redacted/.yarn/cache/es-iterator-helpers-npm-1.0.12-35df79bd02-df1800a64b.zip/node_modules/es-iterator-helpers/Iterator.from/)  Require stack: - redacted/.yarn/cache/es-iterator-helpers-npm-1.0.12-35df79bd02-df1800a64b.zip/node_modules/es-iterator-helpers/Iterator.from/index.js - redacted/.yarn/__virtual__/eslint-plugin-react-virtual-df620cb600/0/cache/eslint-plugin-react-npm-7.33.2-08f77ebc15-b4c3d76390.zip/node_modules/eslint-plugin-react/lib/util/Components.js - redacted/.yarn/__virtual__/eslint-plugin-react-virtual-df620cb600/0/cache/eslint-plugin-react-npm-7.33.2-08f77ebc15-b4c3d76390.zip/node_modules/eslint-plugin-react/lib/rules/boolean-prop-naming.js - redacted/.yarn/__virtual__/eslint-plugin-react-virtual-df620cb600/0/cache/eslint-plugin-react-npm-7.33.2-08f77ebc15-b4c3d76390.zip/node_modules/eslint-plugin-react/lib/rules/index.js - redacted/.yarn/__virtual__/eslint-plugin-react-virtual-df620cb600/0/cache/eslint-plugin-react-npm-7.33.2-08f77ebc15-b4c3d76390.zip/node_modules/eslint-plugin-react/configs/all.js - redacted/.yarn/__virtual__/eslint-plugin-react-virtual-df620cb600/0/cache/eslint-plugin-react-npm-7.33.2-08f77ebc15-b4c3d76390.zip/node_modules/eslint-plugin-react/index.js - redacted/.yarn/cache/@eslint-eslintrc-npm-2.1.2-feb0771c9f-bc742a1e3b.zip/node_modules/@eslint/eslintrc/dist/eslintrc.cjs Referenced from: redacted/.yarn/__virtual__/eslint-config-next-virtual-3dd005a3fc/0/cache/eslint-config-next-npm-13.4.16-745205b385-c4b6849c4b.zip/node_modules/eslint-config-next/index.js`

Looks like there's a missing dependency on `call-bind`.

**Comment by lewandom** [comment]
Further down the road, it also needs the following deps:
- `define-properties`
- `get-intrinsic`
- `has-property-descriptors`

**Comment by YunKukPark** [comment]
https://www.npmjs.com/package/eslint-plugin-react

It seems that es-iterator-helpers was added when the library was updated six hours ago.
I'm also looking for a solution.

![image](https://github.com/es-shims/iterator-helpers/assets/53929065/1ba0ce6e-fc3a-4f5d-b272-9f2642e93fc0)

**Comment by lewandom** [comment]
@YunKukPark an ugly workaround is to install the missing packages (`call-bind`, `define-properties`, `get-intrinsic` and `has-property-descriptors`) as dev deps.

**Comment by YunKukPark** [comment]
@lewandom It's working well. I think I should proceed like this for now.
Thank you for your help 🙇🏻‍♂️

**Comment by ljharb** [comment]
I’ll have a fix out shortly.
