### ISSUE TITLE
TypeError: `[[GeneratorState]]` is not present on `O`

### ISSUE THREAD

**Issue by hibachrach** [es-shims/iterator-helpers#4]
Minimal example:

Detected this in `eslint-plugin-react@7.33.2`
```js
// minimal-example.js
const map = require('es-iterator-helpers/Iterator.prototype.map');

function* myGenerator() {
  yield 1;
  yield 2;
  yield 3;
}

const mapped = map(myGenerator(), (x) => x ** 2);
console.log(mapped);
```

This triggers this error:
```
TypeError: `[[GeneratorState]]` is not present on `O`
    at Object.assert (redacted/node_modules/es-iterator-helpers/node_modules/internal-slot/index.js:19:10)
    at GeneratorStart (redacted/node_modules/es-iterator-helpers/aos/GeneratorStart.js:14:7)
    at CreateIteratorFromClosure (redacted/node_modules/es-iterator-helpers/aos/CreateIteratorFromClosure.js:45:2)
    at myGenerator.map (redacted/node_modules/es-iterator-helpers/Iterator.prototype.map/implementation.js:76:15)
    at Object.<anonymous> (redacted/minimal-example.js:9:16)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
```

**Comment by ljharb** [comment]
Thanks - native generators indeed won't have my polyfill's custom slots, but it makes sense to auto-detect these if possible and `Iterator.from` them for you (a workaround for now is to pass them into `Iterator.from()` first)

**Comment by ljharb** [comment]
hmm, actually - @hibachrach can you confirm what exact version of `es-iterator-helpers` you have installed, and which package manager CLI you're using?

**Comment by hibachrach** [comment]
Sure!
* `es-iterator-helpers`: `1.0.14`
* `yarn`: `3.4.1` (w/o PnP)
* `node`: `16.18.1`

**Comment by ljharb** [comment]
With the only difference being yarn, your OP passes in my repl in both node 16 and 20.

Can you confirm the result of `require('es-iterator-helpers/package.json').version` in your REPL is as expected, and `npm explain es-iterator-helpers` only has one copy?

**Comment by hibachrach** [comment]
```
$ npm explain es-iterator-helpers
es-iterator-helpers@1.0.14 dev
node_modules/es-iterator-helpers
  es-iterator-helpers@"^1.0.12" from eslint-plugin-react@7.33.2
  node_modules/eslint-plugin-react
    dev eslint-plugin-react@"^7.33.2" from the root project

$ node
Welcome to Node.js v16.18.1.
Type ".help" for more information.
> require('es-iterator-helpers/package.json').version
'1.0.14'
> 
```

**Comment by hibachrach** [comment]
Perhaps the issue is in one if `es-iterator-helpers`'s dependencies... This is what is listed in my yarn lock file.
```
    asynciterator.prototype: ^1.0.0
    call-bind: ^1.0.2
    define-properties: ^1.2.0
    es-abstract: ^1.22.1
    es-set-tostringtag: ^2.0.1
    function-bind: ^1.1.1
    get-intrinsic: ^1.2.1
    globalthis: ^1.0.3
    has-property-descriptors: ^1.0.0
    has-proto: ^1.0.1
    has-symbols: ^1.0.3
    internal-slot: ^1.0.5
    iterator.prototype: ^1.1.0
    safe-array-concat: ^1.0.0
```
 Let me see what each of these resolves to.

**Comment by hibachrach** [comment]
```
asynciterator.prototype/package.json 1.0.0
call-bind/package.json 1.0.2
define-properties/package.json 1.1.4
es-abstract/package.json 1.22.1
es-set-tostringtag/package.json 2.0.1
function-bind/package.json 1.1.1
get-intrinsic/package.json 1.2.1
globalthis/package.json 1.0.3
has-property-descriptors/package.json 1.0.0
has-proto/package.json 1.0.1
has-symbols/package.json 1.0.3
internal-slot/package.json 1.0.3
iterator.prototype/package.json 1.1.0
safe-array-concat/package.json 1.0.0
```

**Comment by hibachrach** [comment]
huh, why is `internal-slot` resolving incorrectly? if that's the problem then apologies for the trouble i've caused as that's likely on my end.

**Comment by hibachrach** [comment]
nope i get the same error when internal-slot resolves to 1.0.5.

**Comment by ljharb** [comment]
Indeed, this is a yarn bug, I assume - please file it there. Since we explicitly require ^1.0.5, it's an error to provide 1.0.3.

**Comment by hibachrach** [comment]
Unfortunately i get the same problem when it uses 1.0.5.

**Comment by ljharb** [comment]
I'm still pretty convinced it's a yarn bug since I can't reproduce the problem with npm :-/ i'll reopen tho until we can figure it out.

**Comment by hibachrach** [comment]
It's not a yarn bug as I'm unable to reproduce it in an isolated context with yarn either, but to be honest i'm not sure what it could be. I'll close this as it seems to be specific to my codebase. Thanks for your help.

**Comment by nerdyman** [comment]
For anyone running into this with pnpm try running `pnpm dedupe`.

**Comment by Alain1405** [comment]
> pnpm dedupe

I am having this issue with `bun` and there is no `dedupe` command as far as I know. Still you can use `npm dedupe` and then remove `package.lock` and that fixes the issue.

**Comment by kitsunekyo** [comment]
```
❯ yarn --version
1.22.19
```

i had to manually change `internal-slot` to `^1.0.5`, and `es-iterator-helpers` to `^1.0.15` in my `yarn.lock`. extremely cumbersome.

`eslint-plugin-jsx-a11y` and `eslint-plugin-react` were throwing the `GeneratorState` error

**Comment by casperbrike** [comment]
We had exactly the same problem both locally and on our CI (yarn v1.22.19). This helped us resolve the issue:
```
yarn remove eslint-plugin-react 
yarn add eslint-plugin-react@latest --dev
```

I assume `yarn add` does something similar to `npm dedupe` and it fixes the problem

**Comment by aray12** [comment]
We are also running into this. The removing and adding didn't work for us. Our solution was to force yarn to also resolve to v1.0.5 using [yarn selective resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/)

```json
  "resolutions": {
    "internal-slot": "1.0.5"
  }
```

**Comment by ljharb** [comment]
Has anyone filed this bug on yarn? That's how to get it properly fixed.

**Comment by kitsunekyo** [comment]
> We are also running into this. The removing and adding didn't work for us. Our solution was to force yarn to also resolve to v1.0.5 using [yarn selective resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/)
> 
> ```json
>   "resolutions": {
>     "internal-slot": "1.0.5"
>   }
> ```

you dont have to pin the specific version. you can specify that you want anything above 1.0.5. that way you don't ride on an outdated version.

```json
   "resolutions": {
     "internal-slot": "^1.0.5"
   }
```
