### ISSUE TITLE
IteratorStepValue breaks with latest es-abstract

### ISSUE THREAD

**Issue by AviVahl** [es-shims/iterator-helpers#5]
`assertRecord` seems to not accept the first parameter anymore:
https://github.com/ljharb/es-abstract/commit/87c340d2f72bb5f6b1e46460ed219dd47cd11a09#diff-3ee5b405328c5bff19b033f6d86bd5ffcf3698a7fadae6df8e4090aed9c8c250

saw this because `eslint-plugin-react` uses this package and broke when project picked up the latest `es-abstract`

**Comment by ljharb** [comment]
Thanks, I'll fix it asap.

**Comment by ljharb** [comment]
Fixed, and v1.0.17 released.

**Comment by DemonICOLI** [comment]
I can confirm this is solved
